### PR TITLE
PTBR Locale

### PR DESCRIPTION
**Pull request by fuyukihidekii**
* Initial Brazilian Portuguese translation

### CODE REVIEW

**Comment by xdsopl** [comment]
It is better not to translate the DISCLAIMER. It is a legal text and we would need lawyers to check the translation.

**Comment by xdsopl** [comment]
Thanks, I will replace the disclaimer with the English text

**Comment by blryface** [comment]
hi @fuyukihidekii pls don't pr translations to any project if you're just gonna lazily put it through translation software thanks obrigado

**Comment by blryface** [comment]
(my comment was mean I'm sorry)

**Comment by fuyukihidekii** [comment]
> (my comment was mean I'm sorry)

It's okay kid.
you're free to contribute a better translation if you really want to.

be safe.

**Pull request merged**
