### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by fossdd**
With this you have the fastlane metadata in your repo and we can continue the [RFP](https://gitlab.com/fdroid/rfp/-/issues/1654) for the [F-Droid store](https://f-droid.org/).

Would great if you support the inclusion.

After that please re-tag your release.

### CODE REVIEW

**Comment by xdsopl** [comment]
Can you please make sure that the five supported mode lines are not merged into one line, like it is rendered in the description I saw here:
https://gitlab.com/fdroid/rfp/-/issues/1654
Otherwise I would be happy to to support the inclusion on the fdroid store.

**Comment by fossdd** [comment]
Yes, the GitLab Issue descriptions uses Markdown. And in Markdown is it usual to that a new line meeds two new lines.

The F-Droid description offers basic HTML tags, so with https://github.com/xdsopl/robot36/pull/6/commits/1c086f3312f276bbd4e40d42344a9566802a6f49 you should get it as a list

**Comment by xdsopl** [comment]
Thanks.
Is the ```title.txt``` not missing?
It should have the following content: ```Robot36 - SSTV Image Decoder```

**Comment by IzzySoft** [comment]
Further note that F-Droid itself will replace each line break with a `<br>`, so I strongly suggest collapsing subsequent empty lines to a single one each, like

```markdown
Following modes are supported:

<ul><li>Robot Modes: 36 & 72</li>
<li>PD Modes: 50, 90, 120, 160, 180, 240 & 290</li>
<li>Martin Modes: 1 & 2</li>
<li>Scottie Modes: 1, 2 & DX</li>
<li>Wraase Mode: SC2 180</li></ul>

Old B/W or unsupported modes can be viewed in "Raw Mode".
```

Further, what is now `short_description.txt` should be `title.txt` – our linter will otherwise reject it as it matches the app name. `short_description.txt` should be a short *description* of what the app does, like "decode Slow-Scan Television messages".

**Comment by xdsopl** [comment]
Thank you for the explanations.
Short description should be ```SSTV Image Decoder```

**Comment by xdsopl** [comment]
Okay, I see your point about the acronym ```SSTV``` being too cryptic to most people.
May I suggest the following: ```Image decoder for Slow-Scan Television (SSTV) audio signals```

**Comment by xdsopl** [comment]
I just realized this was a bad merge. The short description had encoder instead of decoder in it.

**Comment by fossdd** [comment]
Oh, that you can edit it. And then re-tag it, so that at the latest tag of a version, all is right.

**Comment by xdsopl** [comment]
Thanks, I just merged the corrected commit and made the ```v1.44-fastlane``` tag for you.

**Comment by IzzySoft** [comment]
Thanks to both of you!

**Pull request merged**
