### PR TITLE
Add Chinese Simplified Translation

### PR DESCRIPTION
**Pull request by WeiguangTWK**
Add translation and make some strings "untranslatable"

DE BG7QWH, 73 for you and your awsome app!

Screenshot

### CODE REVIEW

**Comment by xdsopl** [comment]
Thank you for the translations. I also added translations for the Channel Select menu, the Privacy Policy and About pages. Can you please check if that looks alright?

**Comment by WeiguangTWK** [comment]
> Thank you for the translations. I also added translations for the Channel Select menu, the Privacy Policy and About pages. Can you please check if that looks alright?



@xdsopl  That translation is correct when translated directly. I'm confused about what the "channel select" menu actually control and that's the reason why I left the translation of that part blank. Could you explain that for me?

As for the "about" site and "privacy policy" site, I left them in English for I don't want to cause misunderstanding and lead to legal problem, your translation of that part is also ok

**Comment by xdsopl** [comment]
> I'm confused about what the "channel select" menu .. Could you explain that for me?

Default means single channel microphone input. Unfortunately with stereo microphones, some devices do fancy audio processing when using Default, which ruins the signal. So you need to choose either First or Second channel instead to avoid the processing.

Because there is no exact definition of Left of Right audio channel, I used First and Second channel for devices with more than one microphone.

Summation means that both First and Second channel is recorded and added to a single Mono stream and used for decoding.  You actually gain a better signal this way if both microphones have the exact same distance to the audio source.

Analytic signal means that instead of just using a singe channel real signal as input (Default, First, Second or Summation) and using the Hilbert transformation internally to get the Analytic signal we need, we can provide the real (in-phase) component from the First channel and the imaginary (quadrature) component from the Second channel. This allows us to use very simple quadrature product receivers like a Tayloe detector.

> As for the "about" site and "privacy policy" site, I left them in English

Wise choice. All legal stuff should be left to lawyers, which I am not.

> your translation of that part is also ok

Thank you.

BTW, you should force update your repository, then GitHub should recognize this PR as a done deal.

**Comment by WeiguangTWK** [comment]
@xdsopl  Thank you for your detailed explanation  :)  Maybe you can create a new partition called "Help" and add these explanations above for users to have a better understanding of your awesome software

Have a nice day!

**Comment by xdsopl** [comment]
I am planing on making a YouTube video instead. Thank you and have a nice day, too.

**Comment by WeiguangTWK** [comment]
> I am planing on making a YouTube video instead. Thank you and have a nice day, too.


@xdsopl  Since YouTube is unreachable in China, may I "carry" your video to another video platform (like BiliBili)? I will note the link to the original video

**Comment by xdsopl** [comment]
Sure, I can send you the video file. I can also upload on TikTok. Does TikTok work for you as well?

**Comment by WeiguangTWK** [comment]
TikTok works and if you send me your video file then I will send it to BiliBili (a video platform which is popular among young people in China)

Here's my own BiliBili space https://space.bilibili.com/75633948/

**Comment by xdsopl** [comment]
Cool, Translating the page works. This is my TikTok: https://www.tiktok.com/@xdsopl

**Comment by WeiguangTWK** [comment]
> Cool, Translating the page works. This is my TikTok: https://www.tiktok.com/@xdsopl


Nice but I noticed something, the TikTok you are using is "TikTok Global", which is quite different from the one Chinese use. And of course Chinese cannot access TiKToK global, they only have access to TikTok China (https://www.douyin.com/)

Since I don't use platform like TikTok so I will contact other people who runs subscription account about ham Radio in Wechat and TikTok China

**Comment by xdsopl** [comment]
OMG the Chinese TikTok is so much better than the global one. I barely watch global TikTok as the recommendations are simply garbage. Maybe I should pay attention to the Chinese TikTok and even better, Chinese BiliBili then?

**Comment by WeiguangTWK** [comment]
> OMG the Chinese TikTok is so much better than the global one.

True lol. 

>Maybe I should pay attention to the global TikTok and even better, BiliBili then?

BiliBili is also divided into Chinese version and global version and  they are also separated and isolated. The link I mentioned before is of course BiliBili China.

Bilibili China is mainly focus on Chinese user, maybe I think is better focus on global video platform like YouTube instead of this one

But if you are interested in running an account in Chinese video platform, it still a nice choice to do that because as far as I know there are a lot of Chinese hams use BiliBili and most of them are young people who are full of passion

**Comment by xdsopl** [comment]
I of course meant I should pay more attention to the Chinese TikTok and BiliBili platforms. The divide is kinda sad but understandable: The self destructive stuff on western platforms cannot be ignored anymore since a decade or so. I have to block so many channels on YouTube to keep it a happy place, you wouldn't believe.

**Comment by WeiguangTWK** [comment]
> I of course meant I should pay more attention to the Chinese TikTok and BiliBili platforms. The divide is kinda sad but understandable: The self destructive stuff on western platforms cannot be ignored anymore since a decade or so. I have to block so many channels on YouTube to keep it a happy place, you wouldn't believe.

I feel the same as you , I have used the global video platform for a while (of course using a VPN service), after a while I find myself can not stay on that platform for more time since the content of there is not quite quality

There might be some problem when you are using these Chinese localized platforms, if you finally decided to run Chinese video accounts I will assist you to register and use

**Comment by xdsopl** [comment]
Thank you for that offer. I will contact you.

**Comment by WeiguangTWK** [comment]
> Thank you for that offer. I will contact you.

OK, 22:00 UTC+8 so good night, 73 from Guilin City

**Comment by xdsopl** [comment]
16:00 here, have a good night.

**Pull request closed without merging**
